services:
  db:
    restart: "no"

  adminer:
    restart: "no"

  backend:
    restart: "no"
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app/backend
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild
    # TODO: remove once coverage is done locally
    volumes:
      - ./backend/htmlcov:/app/backend/htmlcov
    environment:
      EMAILS_FROM_EMAIL: "noreply@example.com"

  frontend:
    restart: "no"

  playwright:
    build:
      context: .
      dockerfile: frontend/Dockerfile.playwright
      args:
        - VITE_API_URL=http://backend:8000
        - NODE_ENV=production
    ipc: host
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://backend:8000
      - CI=${CI:-}
    volumes:
      - ./frontend/blob-report:/app/frontend/blob-report
      - ./frontend/test-results:/app/frontend/test-results
    ports:
      - "9323:9323"
